### ISSUE TITLE
The interpol.  often crash in Ras..... Pi 4

### ISSUE THREAD

**Issue by jlivingstonsg** [makerportal/AMG8833_IR_cam#1]
Hi.
The interpol crash often.
We use Raspberry pi 4.

Here is the warning we get in   Thonny Python IDE .
----

/home/pi/Hämtningar/AMG8833_IR_cam-main/examples/IR_cam_interp.py:68: MatplotlibDeprecationWarning: 
The set_window_title function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. <br> 
Use `.FigureManagerBase.set_window_title` or GUI-specific methods instead.
  fig.canvas.set_window_title('AMG8833 Image Interpolation')
Traceback (most recent call last):
  File "/home/pi/Hämtningar/AMG8833_IR_cam-main/examples/IR_cam_interp.py", line 83, in <module>
    status,pixels = sensor.read_temp(pix_to_read) # read pixels with status
  File "../amg8833_i2c.py", line 125, in read_temp
    raw = self.device.read16(GE_PIXEL_BASE + (i << 1))
  File "../amg8833_i2c.py", line 92, in read16
    result = self._bus.read_word_data(self._address,register) & 0xFFFF
OSError: [Errno 5] In/ut-fel

-----

Any solution?

Regards from Sweden
------

**Comment by jlivingstonsg** [comment]
Hi again.

I tried this 
----------------------------
fig.canvas.setWindowTitle('AMG8833 Image Interpolation')
-------------------------------
and now it works.
No warnings and no crashes for some time now.  :)

Regards from Sweden
